language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 10.13
  - 12
  - node
install: npm install
script:
  - npm run validate
  - npx codecov@3
  - cd example/react-fundamentals && npm run setup
branches:
  only:
    - master
    - next

jobs:
  include:
    - stage: release
      node_js: 12
      script: kcd-scripts travis-release
